### ISSUE TITLE
LIMS usage

### ISSUE THREAD

**Issue by jcgrenier** [ewels/labrador#15]
Hi @ewels,

I don't know if you are aware of any team that could have adapted your amazing tool for their own internal usage. What I mean by that, is to 

1) adapt it so we can get links to samples on local servers instead of the GEO server
2) Be able to import a table (a text file) instead of importing using a SRA number
3) Put more informations about already processed samples, like a way to import QC files done with MultiQC for example and put information about the pipeline used for these samples/project

In fact, it would be more of a way to put informations about the samples rather than processing the samples themselves. Having not found any LIMS that can suit my needs and finding that yours is better looking and possibly having better potential, I might try spending some time improving those points.

Thanks for your input and your future help for this! 

JC

**Comment by darogan** [comment]
Hi @jcgrenier,

My updates to Labrador go some way to solving #1 and #3 (MultiQC, PDF reports, Excel files) and I use it as part of a core bioinformatics facility to share date with individual research groups for a wide range of NGS projects

Russell

**Comment by jcgrenier** [comment]
Hi @darogan ,

Thanks for responding! By your updates, do you mean the version you have under your github repo6
https://github.com/darogan/labrador
I actually installed this one, but not actually finding the way to get link on local servers. Unless you put it in any other field?

Thanks for your help!

JC

**Comment by ewels** [comment]
Hi @jcgrenier,

I imagine that Russell is talking about his fork, yes. It will soon to be the same as this main repo (he has an [open pull request](https://github.com/ewels/labrador/pull/14) to bring his changes in).

If I'm honest, I'm a little hesitant about using Labrador as a LIMS, mainly because it was never really intended for that. But I guess if you find it useful in that capacity then that's great 😄  At the Babraham we used the [Sierra LIMS](http://www.bioinformatics.babraham.ac.uk/projects/sierra/) for in house projects, Labrador was just for public datasets.

But yes, I don't see why the updates you suggest shouldn't be possible. Fantastic if @darogan has already implemented most of it. The main problem is that I don't really have time to make any remaining changes for you - I'm happy to keep maintaining it and accept pull requests, but I can't really justify spending a lot of time on development for it when my facility doesn't use it.

Phil
