### ISSUE TITLE
Link on the Babraham Bioinformatics to this github project

### ISSUE THREAD

**Issue by rene-rex** [ewels/labrador#7]
Hello

I had a hard time finding this page with the recent version coming from http://www.bioinformatics.babraham.ac.uk/projects/labrador/. Is it possible to add a link there pointing to this github project?

**Comment by ewels** [comment]
Hi @rene-rex 

Yup, good idea. I moved this project to GitHub in a bit of a rush and haven't done much development work on it since - I had thought that not much had changed since the Babraham page was updated, but looking now it seems that the Babraham page is a version behind.

@s-andrews or @FelixKrueger - could one of you mind updating the Babraham Labrador projects page with a link to the Labrador GitHub releases page please? https://github.com/ewels/labrador/releases

Phil

**Comment by s-andrews** [comment]
OK, done.  I¹ve also updated the documentation and README links to point to the GitHub equivalents.

Simon.

**Comment by ewels** [comment]
Fantastic - thanks Simon!

**Comment by rene-rex** [comment]
Wow, that was fast. Thank you everyone!
